version: 0.2.0.{build}
image: Visual Studio 2017

install:
  - ps: |
      Install-Module PSDocs.Dsc -MinimumVersion 0.3.0 -Scope CurrentUser -Force | Out-Null

build_script:
- ps: .\scripts\build.ps1 -Module DevOpsKitDsc

test_script:
- ps: .\scripts\test.ps1